version: "3.9"  # Adjust if using a different docker-compose version

services:
  djangoapp:
    build: .  # Build the image from the current directory (context)
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - .:/code   # Mount the current directory as /code volume in the container
   # Optional: Enable Django output buffering

  # Add a database service here (e.g., Postgres)
  # ...
